steps:
  # Build step
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/deepseek-inference-api:gemma2b
      - "-t"
      - gcr.io/$PROJECT_ID/deepseek-inference-api:latest
      - "-f"
      - Dockerfile
      - .
    secretEnv: ["HF_TOKEN"]

  # Push step
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/deepseek-inference-api:gemma2b

  # Push latest tag
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/deepseek-inference-api:latest

# Image outputs
images:
  - gcr.io/$PROJECT_ID/deepseek-inference-api:gemma2b
  - gcr.io/$PROJECT_ID/deepseek-inference-api:latest

# Available Secrets
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest
      env: "HF_TOKEN"

# Build options
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 200 # Increased disk space otherwise the model built on cloud build exceeds default space
  env:
    - HF_HUB_ENABLE_HF_TRANSFER=1 # Enable faster downloads
    - HF_HUB_DISABLE_PROGRESS_BARS=1 # Reduce log noise
