version: '3.8'

services:
  inference-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: deepseek-inference-api:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    volumes:
      - model-cache:/root/.cache/huggingface  # Cache Hugging Face models

volumes:
  model-cache:  # Persistent volume for model cache
